### ISSUE TITLE
analyse_sc_clusters() not found

### ISSUE THREAD

**Issue by aditisk** [reactome/ReactomeGSA#13]
Hello, I'm a new user and I tried to follow the single cell analysis vignette (http://bioconductor.org/packages/release/bioc/vignettes/ReactomeGSA/inst/doc/analysing-scRNAseq.html). I installed the package but I'm getting the error pasted below when I try to run the 1st step with my own Seurat object.

`Error in analyse_sc_clusters(cscc, verbose = TRUE) : 
  could not find function "analyse_sc_clusters"`

Am I missing something during installation ? How can I get past this ? Thanks.

`> session_info()
─ Session info ───────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       macOS Catalina 10.15.2      
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-11-04                  

─ Packages ───────────────────────────────────────────────────────────────────────────
 package      * version  date       lib source        
 ape            5.3      2019-03-17 [1] CRAN (R 3.6.0)
 assertthat     0.2.1    2019-03-21 [1] CRAN (R 3.6.0)
 backports      1.1.6    2020-04-05 [1] CRAN (R 3.6.2)
 BiocManager    1.30.10  2019-11-16 [1] CRAN (R 3.6.0)
 bit            1.1-15.2 2020-02-10 [1] CRAN (R 3.6.0)
 bit64          0.9-7    2017-05-08 [1] CRAN (R 3.6.0)
 bitops         1.0-6    2013-08-17 [1] CRAN (R 3.6.0)
 callr          3.4.3    2020-03-28 [1] CRAN (R 3.6.2)
 caTools        1.18.0   2020-01-17 [1] CRAN (R 3.6.0)
 cli            2.0.2    2020-02-28 [1] CRAN (R 3.6.0)
 cluster        2.1.0    2019-06-19 [1] CRAN (R 3.6.3)
 codetools      0.2-16   2018-12-24 [1] CRAN (R 3.6.3)
 colorspace     1.4-1    2019-03-18 [1] CRAN (R 3.6.0)
 cowplot        1.0.0    2019-07-11 [1] CRAN (R 3.6.0)
 crayon         1.3.4    2017-09-16 [1] CRAN (R 3.6.0)
 data.table     1.12.8   2019-12-09 [1] CRAN (R 3.6.0)
 desc           1.2.0    2018-05-01 [1] CRAN (R 3.6.0)
 devtools     * 2.3.1    2020-07-21 [1] CRAN (R 3.6.2)
 digest         0.6.25   2020-02-23 [1] CRAN (R 3.6.0)
 dplyr          0.8.5    2020-03-07 [1] CRAN (R 3.6.0)
 ellipsis       0.3.0    2019-09-20 [1] CRAN (R 3.6.0)
 fansi          0.4.1    2020-01-08 [1] CRAN (R 3.6.0)
 farver         2.0.3    2020-01-16 [1] CRAN (R 3.6.0)
 fitdistrplus   1.0-14   2019-01-23 [1] CRAN (R 3.6.0)
 fs             1.4.1    2020-04-04 [1] CRAN (R 3.6.2)
 future         1.17.0   2020-04-18 [1] CRAN (R 3.6.2)
 future.apply   1.5.0    2020-04-17 [1] CRAN (R 3.6.2)
 gdata          2.18.0   2017-06-06 [1] CRAN (R 3.6.0)
 ggplot2        3.3.0    2020-03-05 [1] CRAN (R 3.6.0)
 ggrepel        0.8.2    2020-03-08 [1] CRAN (R 3.6.0)
 ggridges       0.5.2    2020-01-12 [1] CRAN (R 3.6.0)
 globals        0.12.5   2019-12-07 [1] CRAN (R 3.6.0)
 glue           1.4.0    2020-04-03 [1] CRAN (R 3.6.2)
 gplots         3.0.3    2020-02-25 [1] CRAN (R 3.6.0)
 gridExtra      2.3      2017-09-09 [1] CRAN (R 3.6.0)
 gtable         0.3.0    2019-03-25 [1] CRAN (R 3.6.0)
 gtools         3.8.2    2020-03-31 [1] CRAN (R 3.6.2)
 hdf5r          1.3.2    2020-03-25 [1] CRAN (R 3.6.0)
 htmltools      0.4.0    2019-10-04 [1] CRAN (R 3.6.0)
 htmlwidgets    1.5.1    2019-10-08 [1] CRAN (R 3.6.0)
 httr           1.4.1    2019-08-05 [1] CRAN (R 3.6.0)
 ica            1.0-2    2018-05-24 [1] CRAN (R 3.6.0)
 igraph         1.2.5    2020-03-19 [1] CRAN (R 3.6.0)
 irlba          2.3.3    2019-02-05 [1] CRAN (R 3.6.0)
 jsonlite       1.6.1    2020-02-02 [1] CRAN (R 3.6.0)
 KernSmooth     2.23-17  2020-04-26 [1] CRAN (R 3.6.2)
 labeling       0.3      2014-08-23 [1] CRAN (R 3.6.0)
 lattice        0.20-41  2020-04-02 [1] CRAN (R 3.6.2)
 lazyeval       0.2.2    2019-03-15 [1] CRAN (R 3.6.0)
 leiden         0.3.3    2020-02-04 [1] CRAN (R 3.6.0)
 lifecycle      0.2.0    2020-03-06 [1] CRAN (R 3.6.0)
 listenv        0.8.0    2019-12-05 [1] CRAN (R 3.6.0)
 lmtest         0.9-37   2019-04-30 [1] CRAN (R 3.6.0)
 lsei           1.2-0    2017-10-23 [1] CRAN (R 3.6.0)
 magrittr       1.5      2014-11-22 [1] CRAN (R 3.6.0)
 MASS           7.3-51.6 2020-04-26 [1] CRAN (R 3.6.2)
 Matrix         1.2-18   2019-11-27 [1] CRAN (R 3.6.3)
 memoise        1.1.0    2017-04-21 [1] CRAN (R 3.6.0)
 munsell        0.5.0    2018-06-12 [1] CRAN (R 3.6.0)
 nlme           3.1-147  2020-04-13 [1] CRAN (R 3.6.2)
 npsurv         0.4-0    2017-10-14 [1] CRAN (R 3.6.0)
 patchwork      1.0.0    2019-12-01 [1] CRAN (R 3.6.0)
 pbapply        1.4-2    2019-08-31 [1] CRAN (R 3.6.0)
 pillar         1.4.3    2019-12-20 [1] CRAN (R 3.6.0)
 pkgbuild       1.0.7    2020-04-25 [1] CRAN (R 3.6.2)
 pkgconfig      2.0.3    2019-09-22 [1] CRAN (R 3.6.0)
 pkgload        1.0.2    2018-10-29 [1] CRAN (R 3.6.0)
 plotly         4.9.2.1  2020-04-04 [1] CRAN (R 3.6.2)
 plyr           1.8.6    2020-03-03 [1] CRAN (R 3.6.0)
 png            0.1-7    2013-12-03 [1] CRAN (R 3.6.0)
 prettyunits    1.1.1    2020-01-24 [1] CRAN (R 3.6.0)
 processx       3.4.2    2020-02-09 [1] CRAN (R 3.6.0)
 ps             1.3.2    2020-02-13 [1] CRAN (R 3.6.0)
 purrr          0.3.4    2020-04-17 [1] CRAN (R 3.6.2)
 R6             2.4.1    2019-11-12 [1] CRAN (R 3.6.0)
 RANN           2.6.1    2019-01-08 [1] CRAN (R 3.6.0)
 RColorBrewer   1.1-2    2014-12-07 [1] CRAN (R 3.6.0)
 Rcpp           1.0.4.6  2020-04-09 [1] CRAN (R 3.6.3)
 RcppAnnoy      0.0.16   2020-03-08 [1] CRAN (R 3.6.0)
 ReactomeGSA  * 1.0.0    2019-10-29 [1] Bioconductor  
 remotes        2.2.0    2020-07-21 [1] CRAN (R 3.6.2)
 reshape2       1.4.4    2020-04-09 [1] CRAN (R 3.6.2)
 reticulate   * 1.15     2020-04-02 [1] CRAN (R 3.6.2)
 rlang          0.4.5    2020-03-01 [1] CRAN (R 3.6.0)
 ROCR           1.0-7    2015-03-26 [1] CRAN (R 3.6.0)
 rprojroot      1.3-2    2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi     0.11     2020-02-07 [1] CRAN (R 3.6.0)
 rsvd           1.0.3    2020-02-17 [1] CRAN (R 3.6.0)
 Rtsne          0.15     2018-11-10 [1] CRAN (R 3.6.0)
 scales         1.1.0    2019-11-18 [1] CRAN (R 3.6.0)
 sctransform    0.2.1    2019-12-17 [1] CRAN (R 3.6.0)
 sessioninfo    1.1.1    2018-11-05 [1] CRAN (R 3.6.0)
 Seurat       * 3.1.5    2020-04-16 [1] CRAN (R 3.6.2)
 stringi        1.4.6    2020-02-17 [1] CRAN (R 3.6.0)
 stringr        1.4.0    2019-02-10 [1] CRAN (R 3.6.0)
 survival       3.1-12   2020-04-10 [1] CRAN (R 3.6.2)
 testthat       2.3.2    2020-03-02 [1] CRAN (R 3.6.0)
 tibble         3.0.1    2020-04-20 [1] CRAN (R 3.6.2)
 tidyr          1.0.2    2020-01-24 [1] CRAN (R 3.6.0)
 tidyselect     1.0.0    2020-01-27 [1] CRAN (R 3.6.0)
 tsne           0.1-3    2016-07-15 [1] CRAN (R 3.6.0)
 usethis      * 1.6.0    2020-04-09 [1] CRAN (R 3.6.2)
 uwot           0.1.8    2020-03-16 [1] CRAN (R 3.6.0)
 vctrs          0.2.4    2020-03-10 [1] CRAN (R 3.6.0)
 viridisLite    0.3.0    2018-02-01 [1] CRAN (R 3.6.0)
 withr          2.2.0    2020-04-20 [1] CRAN (R 3.6.2)
 yaml           2.2.1    2020-02-01 [1] CRAN (R 3.6.0)
 zoo            1.8-7    2020-01-10 [1] CRAN (R 3.6.0)`

**Comment by jgriss** [comment]
Hi @aditisk ,

Thanks for your interest in ReactomeGSA!

The reason is that your version of Bioconductor is outdate. I guess you are on Bioconductor 3.10, this function was only added to a later version of our package which is available since Bioconductor 3.11.

In case you do not want to update your whole Bioconductor installation, you can install the latest version of our package directly from GitHub using this code:

```r
# install devtools if needed
if (!require(devtools)) {
  install.packages("devtools")
}

# install the ReactomeGSA package
if (!require(ReactomeGSA)) {
  install_github("reactome/ReactomeGSA")
}
```

**Comment by aditisk** [comment]
Hi @jgriss, thank you for the suggestion. I installed the latest version from Github and I solved the function not found issue. I am getting an error when I'm running this step though:

`
> gsva_result <- analyse_sc_clusters(cscc, verbose = TRUE)
Calculating average cluster expression...
Error in tapply(seq_len(0L), list(cell_ids = c("1", "1", "1", "1", "1",  : 
  arguments must have same length
`

Not sure if this is relevant but my Seurat object is actually an AnnData h5ad file from Scanpy converted to a Seurat object. This messes up the categorical variables sometimes so I'm not sure if that's the source of this error.

I could open a new issue on Github is this is not the proper place for troubleshooting this. Thanks for your help.

**Comment by jgriss** [comment]
Hi @aditisk,

This does indeed point to an issue in your metadata structure.

By default, the analyse_sc_clusters function uses the cell identifiers stored under `Idents`.

Maybe have a look at the structure of the output of the following code:

```r
# make sure identifications match the number of cells
length(Idents(cscc)) == ncol(cscc)

# have a look at the current identifications
head(Idents(cscc))
```

Kind regards,
Johannes

**Comment by aditisk** [comment]
Hi @jgriss thanks for the suggestion. I'll close this for now and re-open if the issue still persists.
