### ISSUE TITLE
Label clusters using plot_gsva_pca

### ISSUE THREAD

**Issue by rpauly** [reactome/ReactomeGSA#15]
I was trying to change the colors to the clusters as:
`plot_gsva_pca(gsva_result, colour=sample, label=TRUE, label.size=3)`
However, no labels come up.
Any suggestions?
Thanks,
Rini

**Comment by jgriss** [comment]
Hi @rpauly ,

The parameters you added to the `plot_gsva_pca` function are actually passed to `prcomp` and do not influence the plot itself.

The function returns a `ggplot` plot which you can adapt using ggplot's normal functions.

Here's an example:

```r
# create the PCA plot
g <- plot_gsva_pca(gsva_result)

# change the colors using ggplot's scale_color_manual function
adapted_colors_plot <- g + scale_color_manual(values=my_colors)

# increase the point size
adapted_point_size <- g + geom_point(size = 5)

# of course, you can combine these settings
my_plot <- g + geom_point(size = 5) + scale_color_manual(values = my_colors)
```

Essentially, you can use all of ggplot's standard functions to adapt the layout of the generated plots.

Hope this helps!

Kind regards,
Johannes
