### ISSUE TITLE
analyse_sc_clusters with the "Error in readBin(3L, raw(0), 32768L) : "

### ISSUE THREAD

**Issue by Charlesyip2016** [reactome/ReactomeGSA#17]
> gsva_result<-analyse_sc_clusters(jerby_b_cells,verbose = TRUE)
Calculating average cluster expression...
Converting expression data to string... (This may take a moment)
Conversion complete
Submitting request to Reactome API...
Compressing request data...
Reactome Analysis submitted succesfully
Mapping identifiers...                                       
Performing gene set analysis using ssGSEA                    
Analysing dataset 'Seurat' using ssGSEA                      
Retrieving result...                                         
Error in readBin(3L, raw(0), 32768L) : 
  transfer closed with outstanding read data remaining

**Comment by jgriss** [comment]
Hi @Charlesyip2016 

Thanks for reporting this!

The error you get points to a network issue. Most of the times it's enough if you simply try again.

Kind regards,
Johannes
