### ISSUE TITLE
Error with curl HTTP access

### ISSUE THREAD

**Issue by maraddatz** [reactome/ReactomeGSA#18]
I am having issues with curl access to Reactome. I suspect this is due to version control across packages, but wondering if you've run into this and have a fix. I got this error when using your sample data as written in the vignette.

Error in curl::curl_fetch_memory(url, handle = handle) : 
  HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)

**Comment by jgriss** [comment]
Hi,

Quite a few users have experienced this issue. It means that the network connection was interrupted. Could you simply try to launch the analysis again?

I believe this worked for everyone until now.

Thanks a lot!

Johannes

On 16 February 2021 16:47:25 CET, maraddatz <notifications@github.com> wrote:
>I am having issues with curl access to Reactome. I suspect this is due
>to version control across packages, but wondering if you've run into
>this and have a fix. I got this error when using your sample data as
>written in the vignette.
>
>Error in curl::curl_fetch_memory(url, handle = handle) : 
>  HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/reactome/ReactomeGSA/issues/18

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by maraddatz** [comment]
Sure enough, I switched to a wired connection and that solved the problem.

Thanks so much!
Michael

**Comment by jgriss** [comment]
Happy to hear it worked!

Johannes

On 16 February 2021 17:46:33 CET, maraddatz <notifications@github.com> wrote:
>Sure enough, I switched to a wired connection and that solved the
>problem.
>
>Thanks so much!
>Michael
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/reactome/ReactomeGSA/issues/18#issuecomment-779964249

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
