### ISSUE TITLE
Typo in tutorial

### ISSUE THREAD

**Issue by vertesy** [reactome/ReactomeGSA#20]
On https://bioconductor.org/packages/release/bioc/vignettes/ReactomeGSA/inst/doc/analysing-scRNAseq.html

It reads:
```r
# install the ReactomeGSA.data package for the example data
if (!require(ReactomeGSA))
  BiocManager::install("ReactomeGSA.data")
```

instead I think it should be `if (!require(ReactomeGSA.data))`
```r
# install the ReactomeGSA.data package for the example data
if (!require(ReactomeGSA.data))
  BiocManager::install("ReactomeGSA.data")
```

**Comment by jgriss** [comment]
@vertesy 

Thanks  a lot! This has been fixed in beba40
