### ISSUE TITLE
Error at too many cells – Cholmod error 'problem too large' 

### ISSUE THREAD

**Issue by vertesy** [reactome/ReactomeGSA#21]
Following the [tutorial](https://bioconductor.org/packages/release/bioc/vignettes/ReactomeGSA/inst/doc/analysing-scRNAseq.html) – worked on the example, tryin on my own data, I get a matrix size related error:
 
```r
>   gsva_result <- analyse_sc_clusters(combined.obj, verbose = TRUE)
Calculating average cluster expression...
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102

> combined.obj
An object of class Seurat 
28439 features across 158666 samples within 2 assays 
Active assay: integrated (2000 features, 2000 variable features)
 1 other assay present: RNA
 3 dimensional reductions calculated: pca, umap, tsne
```

I will try subsetting the dataset to 50%, 25% etc.

––––––––––––––––––––––––––––––
I used to get such errors when I used colSum etc that not explicitly from the  `matrix` package.

**Comment by vertesy** [comment]
Down sampling to 30% solves the issue, however you might want to enable it for larger datasets.

**Comment by jgriss** [comment]
Hi,

It's a memory issue that's actually triggered by Seurat. Unfortunately, the only solution is to run your analysis on a larger machine or reduce the data size.

Kind regards,
Johannes

On 2 June 2021 18:16:12 CEST, Abel Vertesy ***@***.***> wrote:
>Down sampling to 30% solves the issue, however you might want to enable
>it for larger datasets.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/reactome/ReactomeGSA/issues/21#issuecomment-853162779

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
