### ISSUE TITLE
where to find start_reactome_analysis?

### ISSUE THREAD

**Issue by FADHLyemen** [reactome/ReactomeGSA#25]
Hi,
I could not find start_reactome_analysis function. could you help? I need to understand what happen at the API.

if (verbose) message("Submitting request to Reactome API...")
  analysis_id <- start_reactome_analysis(request = request, compress = compress, reactome_url = reactome_url)
  
 Second, if I am interested in specific pathway, how to retrieve its genes?
Third, can I apply same method in KEGG pathways?
Thank you

**Comment by jgriss** [comment]
Hi @FADHLyemen,

Please try to update your version of Bioconductor / ReactomeGSA. The `start_reactome_analysis` function is exported by default and available once you loaded the library.

Unfortunately, we have not yet integrated the gene > pathway mappings in the result object. We're working on it but the feature isn't done yet.

We do not support KEGG but only Reactome pathways.

Kind regards,
Johannes

**Comment by FADHLyemen** [comment]
Thank you, 
my question is how did you compute pathway activity score?
I have some genes and I need to compute the pathway score. 
it is the average expression of these genes grouped by cell types. CODE something like

```
av_counts %>% data.frame()%>%rownames_to_column('sample') %>% filter(sample %in% c('KCNK3','KCNK9')) %>%
column_to_rownames("sample") %>% 
#scale %>% 
colMeans %>%
data.frame(SGLTI=.) 
```

**Comment by jgriss** [comment]
Hi @FADHLyemen ,

I'm not quite sure that I understand your question.

We first use the average expression per cluster, then use this as an input to ssGSEA.

Does this answer your question?

Kind regards,
Johannes
