### ISSUE TITLE
Error: Failed to connect to ReactomeGSA

### ISSUE THREAD

**Issue by FADHLyemen** [reactome/ReactomeGSA#27]
ReactomeGSA worked good but today I got the below error

`Error: Failed to connect to ReactomeGSA at 'https://gsa.reactome.org/: lazy-load database '/home/alakwaaf/anaconda3/envs/cellxgeneNVIP/lib/R/library/curl/R/curl.rdb' is corrupt. Try reverting the ReactomeGSA url to http://gsa.reactome.org using options(reactome_gsa.url = "http://gsa.reactome.org").`

**Comment by jgriss** [comment]
Hi @FADHLyemen ,

This seems to be either a network issue or related to your curl installation. Please have a look at these two options. The error is not caused by the ReactomeGSA code.

Kind regards,
Johannes
