### ISSUE TITLE
reproducibility of the ReactomeGSA

### ISSUE THREAD

**Issue by FADHLyemen** [reactome/ReactomeGSA#28]
Hi, 
I am trying to get pathway scores using ssGSEA for my genes of interest. The problem here that I do not know what is the API is doing, so I try to replicate the results from GSA as following:
What I got form ReactomeGSA is:
![image](https://user-images.githubusercontent.com/23288387/125118079-30f90900-e0bd-11eb-878b-569812f6a10a.png)

Genes in this pathway are:

`event2Ids(event.id = "R-HSA-1299316")`

```
$geneSymbol
[1] "KCNK3" "TASK"  "TASK1" "KCNK9" "TASK3"
```
Genes set

```
gs1=list()
gs1$TWAK=c("KCNK3" ,"TASK",  "TASK1" ,"KCNK9" ,"TASK3")
```

I borrow some code from ReactomeGSA to get avg 

# get the data
```
raw_data <- Seurat::GetAssayData(data_SGLTI, assay = "RNA", slot = "counts")
  
  # get the identis
cell_ids <- as.character( Seurat::Idents(data_SGLTI) )

av_counts <- apply(raw_data, 1, function(row_data) {
    by(row_data, cell_ids, mean)
  })

av_counts_SGLTI <- t( data.frame(av_counts) )
```

Then use GSVA package

`gsva(av_counts_SGLTI, gs1, ssgsea.norm=T,verbose=FALSE,method='ssgsea')`

to get the pathway score

![image](https://user-images.githubusercontent.com/23288387/125118631-f8a5fa80-e0bd-11eb-8829-4fa50e5fe731.png)

I tried to play with many parameters in gsva function but could not get  same results as from `analyse_sc_clusters `function 

I appreciate  your help to generate same results.

Thank you

**Comment by jgriss** [comment]
Dear @FADHLyemen,

Thanks for your interest in Reactome!

You can find the detailed code of the backend here:
https://github.com/reactome/gsa-backend

The file for the gene set variation analysis is this one:
https://github.com/reactome/gsa-backend/blob/master/reactome_analysis_worker/reactome_analysis_worker/analysers/r_gsva_analyser.py

Beware though that we use a different mapping function to map genes to pathways (which uses the Reactome mapping service in between). This most likely explains the differences.

Kind regards,
Johannes

**Comment by FADHLyemen** [comment]
Thank you for your reply.
I still could not get same results as ReactomeGSA.
May be as you mention is the genes-pathways mapping. Could you help me with the list of genes in TWIK-releated acid-sensitive K+channel(TASK) pathway?
I used 
`event2Ids(event.id = "R-HSA-1299316")`

which should get:
`"KCNK3" "TASK"  "TASK1" "KCNK9" "TASK3"`

so what is your genes mapped in your code?

Thank you again for your reply

**Comment by jgriss** [comment]
Dear @FADHLyemen ,

In order to perform the analysis the same way as our tool, your first need to use the Reactome mapping service, map to UniProt identifiers and then use the internal mapping code mentioned above.

Unfortunately, we do not have the resources to support users developing their own analysis tools. But please do feel free to use our tools and code!

Kind regards,
Johannes

**Comment by FADHLyemen** [comment]
@jgriss 
I do not think the problem is in mapping genes to pathways. 
for example Reactome pathway: TWIK-releated acid-sensitive K+ channel (TASK)
https://reactome.org/PathwayBrowser/#/R-HSA-1296071&SEL=R-HSA-1299316&PATH=R-HSA-112316&DTAB=EX
Has only two genes:
"KCNK3" ,"KCNK9"

`gsva(av_counts_SGLTI, gs1, ssgsea.norm=T,verbose=FALSE,method='ssgsea')`

get you:
![image](https://user-images.githubusercontent.com/23288387/125347133-8e44c280-e328-11eb-8603-11361831539f.png)

however ` analyse_sc_clusters(data_SGLTI, verbose = TRUE)`

get you
![image](https://user-images.githubusercontent.com/23288387/125347202-a3b9ec80-e328-11eb-8296-f370decc03e1.png)

I am wondering what other process in ReactomeGSA to get another results rather than gsva?
