### ISSUE TITLE
Error: Failed to connect to ReactomeGSA

### ISSUE THREAD

**Issue by Ankita-1211** [reactome/ReactomeGSA#44]
Hi 

I am facing this error while running reactomeGSA.

Error: Failed to connect to ReactomeGSA at 'https://gsa.reactome.org/: SSL certificate problem: unable to get local issuer certificate. Try reverting the ReactomeGSA url to http://gsa.reactome.org using options(reactome_gsa.url = "http://gsa.reactome.org").

I understand this is an SSL certificate authentication error, could you please guide me in fixing this.

**Comment by jgriss** [comment]
Hi,

Thanks a lot for your interest in ReactomeGSA!

Unfortunately, we are aware of this issue. It's an issue on our cluster.

You can fix it by entering the following command (once) before calling other ReactomeGSA functions:

options(reactome_gsa.url = "http://gsa.reactome.org")

Kind regards,
Johannes

On 15 September 2021 07:40:47 CEST, Ankita Kumari ***@***.***> wrote:
>Hi 
>
>I am facing this error while running reactomeGSA.
>
>Error: Failed to connect to ReactomeGSA at 'https://gsa.reactome.org/: SSL certificate problem: unable to get local issuer certificate. Try reverting the ReactomeGSA url to http://gsa.reactome.org using options(reactome_gsa.url = "http://gsa.reactome.org").
>
>I understand this is an SSL certificate authentication error, could you please guide me in fixing this.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/reactome/ReactomeGSA/issues/44
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jgriss** [comment]
Hi @Ankita-1211 ,

This issue is now resolved.

Kind regards,
Johannes
