### ISSUE TITLE
Request failed (503 - Service Unavailable): Failed to connect to storage system

### ISSUE THREAD

**Issue by Ankita-1211** [reactome/ReactomeGSA#45]
Hi 

I am getting below error on running reactomeGSA

Error in start_reactome_analysis(request = request, compress = compress,  : 
  Request failed (503 - Service Unavailable): Failed to connect to storage system. Please try again in a few minutes.

**Comment by jgriss** [comment]
Hi @Ankita-1211 ,

Thanks a lot for reporting this issue!

We are aware of it and already working on a fix. Unfortunately, it's an issue with our underlying server cluster. It's fixed at the moment but the service may remain unstable for the next few days.

Sorry for the inconvenience!

Kind regards,
Johannes

**Comment by jgriss** [comment]
Hi @Ankita-1211 ,

Our service should be back to normal. Please let us know should you experience and further issues!

Kind regards,
Johannes

**Comment by RefineHALLO** [comment]
Hello, sorry to reopen this issue.

I got same problem on windows10.
I thought analyse_sc_clusters function (and so on) was used on Linux in tutorial, and should I use Linux?

Thank you.

**Comment by RefineHALLO** [comment]
Hello, @jgriss, @Ankita-1211. I am sorry to reopen this issue.
Thank you for this wonderful package.

I got same problem on windows10.
I thought analyse_sc_clusters function (and so on) was used on Linux in tutorial, and should I use it?

Thank you.

**Comment by jgriss** [comment]
Hi @RefineHALLO 

Yes, unfortunately we are aware of this issue.

You can currently bypass it by using our development system:

```r
# Run this command before performing the analysis
options(reactome_gsa.url = "http://gsa-dev.reactome.org")
```

**Comment by RefineHALLO** [comment]
@jgriss Thank you for your reply !
It worked well !!
