### ISSUE TITLE
Request failed (503 - Service Unavailable)

### ISSUE THREAD

**Issue by Luq16** [reactome/ReactomeGSA#58]
Hi,
I was using ReactomeGSA through R. After some time I started getting the error below: 

"Error in start_reactome_analysis(request = request, compress = compress,  : 
  Request failed (503 - Service Unavailable): The number of analysis requests is currently too high. Please try again in a few minutes." 

Thanks.

**Comment by jgriss** [comment]
Hi @Luq16,

We had some periods of very high usage. Our system then reduces the number of accepted analysis requests. The situation is back to normal now and everything should work as expected.

Kind regards,
Johannes
