### ISSUE TITLE
Convert http to https in report download urls

### ISSUE THREAD

**Issue by cqgong** [reactome/ReactomeGSA#59]
When you perform a GSA analysis service and would like to generate the analysis report, the links for downloading the reports are not working well in Chrome duo to it is HTTP download and Chrome has blocked non-secure downloads from HTTPS website. it would be great to convert HTTP to HTTPS to avoid this.

**Comment by jgriss** [comment]
Thanks a lot!

Closing the issue here since we track all API related development in the [gsa-backend](https://github.com/reactome/gsa-backend) repository.

This repo is only used for the R package.
