### ISSUE TITLE
Can we integrate Lipidomics, Metabolomics with RNA-seq, proteomics with ReactomeGSA？

### ISSUE THREAD

**Issue by Shicheng-Guo** [reactome/ReactomeGSA#68]
Dear Team, 

Are we able to integrate Lipidomics, Metabolomics with RNA-seq, proteomics with ReactomeGSA？

Thanks.

Shicheng

**Comment by jgriss** [comment]
Dear @Shicheng-Guo,

Thanks a lot for your interest in ReactomeGSA!

ReactomeGSA uses the [Reactome](https://www.reactome.org) pathway resource in the backend. Unfortunately, we do not (yet) have sufficient data on metabolites and lipids to support analyses for these data types.

Kind regards,
Johannes
