### ISSUE TITLE
Pathway analysis on Spatial data 10x Visium

### ISSUE THREAD

**Issue by cathalgking** [reactome/ReactomeGSA#71]
I have a SpatialExperiment (similar to SingleCellExperiment) object and a Seurat object both containing the same 10x Visium experiment. The experiment objects contains 4 images and associated assay. I have 2 objects because it is easier to integrate 4 images into one object with the SpatialExperiment package. When I try to run 'analyse_sc_clusters' on either object, I get an Error (different error for seu and spe objects). Can this package handle 10x Visium type data? I have dim reduction and clustering calculated in each object but not sure why it is not working.

![reactome](https://user-images.githubusercontent.com/32261323/212835210-eb1ccd51-3932-4535-aaa2-1d116b6aba3d.png)

**Comment by jgriss** [comment]
Hi @cathalgking 

Thanks a lot for your interest in our package!

We never tested the package on spatial data. But what you definitely need is some sort of clustering beforehand which has to be set as the main `Ident`

**Comment by cathalgking** [comment]
I have clustered with PCA and tSNE/UMAP which is contained in the objects.

**Comment by jgriss** [comment]
Hi @cathalgking 

The methods you used are no clusterings yet. PCA is a dimensionality reduction and tSNE/UMAP just 2D embeddings.

You need to run `FindClustes` in Seurat (and the respective methods beforehand) in order to get a clustering result. This can then be used with ReactomeGSA
