### ISSUE TITLE
Statistical significance from single-cell cluster analysis

### ISSUE THREAD

**Issue by LuciaJim** [reactome/ReactomeGSA#72]
Hello!
Congratulations for such a nice package!
After following ReactomeGSA vignette to analyse scRNA-seq data, I would like to know how can I access the p-values from the pathway-level expression per cluster.

Thank you very  much,
Lucia

**Comment by jgriss** [comment]
Hi @LuciaJim 

Thanks a lot for the positive feedback!

The algorithm for the scRNA-seq data is a so-called gene set variation approach. It maps gene-level expression data on the pathway level. For scRNA-seq data this means, that you get one value per pathway and cluster.

To get p-values, you'd now need to f.e. compare two clusters with each other.

This is a bit different to the "findMarkers" function, f.e. in Seurat, where they compare the expression level of individual genes per cell. There, they of course have many values per cluster and can therefore get a p-value.

Kind regards,
Johannes

**Comment by LuciaJim** [comment]
Hi Johannes,
Thanks for the quick response!

As I only have one value per pathway and cluster, does it mean that I could not obtain statistical significance from the pathway-level expression values? or could I additionally carry out statistical significance analysis for f.e. the first 25 most different pathway-level expression values for one cluster vs. another?

Please clarify what you mean by this:
`To get p-values, you'd now need to f.e. compare two clusters with each other.`

Thank you very much,
Lucia

**Comment by jgriss** [comment]
Hi,

In the current implementation you cannot get a significance level from just looking at one cluster. What I meant by my previous post is that you can f.e. compare different clusters with each other.

But you need two groups that you are comparing against each other.

Also, you can compare different sample groups within one cluster between each other.

Does that make sense?

Kind regards,
Johannes

**Comment by jgriss** [comment]
Hi,

The cleanest way to get there is if your cluster is made up of data from multiple samples. What you can then do is to create a new cell property merging the cluster and the sample id.

```R
# using Seurat this would look like this
seurat_obj$combined_id <- paste0(Idents(seurat_obj), "-", seurat_obj$sample_id)

# save the cluster assignment just in case
seurat_obj$cluster <- Idents(seurat_obj)

# use the new id as main identifier
Idents(seurat_obj) <- seurat_obj$combined_id
```
If you perform the analysis now, you'll get one expression value per cluster and sample. Then, you can use a t.test or similar to compare all values of one cluster with another one.

Hope this helps!

**Comment by LuciaJim** [comment]
Great, thanks a lot for looking into this!
