### ISSUE TITLE
ReactomeGSA API not working?

### ISSUE THREAD

**Issue by quyaingo** [reactome/ReactomeGSA#75]
Hello,

I'm trying to perform_reactome_analysis on my ReactomeAnalysisRequest object but got this error:

Error in start_reactome_analysis(request = request, compress = compress,  : 
  Request failed (503 - Service Unavailable): Failed to connect to storage system. Please try again in a few minutes.

Is the public API https://gsa.reactome.org/ not working?

Thank you.

**Comment by jgriss** [comment]
Dear @quyaingo ,

This is a normal process of our system. During high loads the application automatically scales up. Due to technical reasons, during this time, the storage backend is not available. As stated in the error message, the system is automatically available again within a few minutes.

According to our logs, this was the case.

Please let us know, if the error persists!

**Comment by quyaingo** [comment]
Hello,
Yesterday I tried 4 times, 5-10 minutes apart. Just now I tried 3 times, 3-5 minutes apart.
Unfortunately, the error persists. This is with the ReactomeAnalysisRequest object of ~ 200Mb.
When I tried with an object of ~ 1.5Gb, R aborted immediately.

**Comment by jgriss** [comment]
Hi,

Thanks a lot for the added information! Yes, we do have an internal limit on the request size (with a very inadequate error message). We'll adapt the error message in a future release.

But for your case: May I ask what kind of data you are trying to analyse? Maybe we can find a solution then.

Our largest analyses contained complete TCGA datasets with >1000 samples and this worked fine.

Thanks a lot!

Johannes

**Comment by quyaingo** [comment]
Hi Johannes,

My largest data have 4 sets of immune cells, each under 2 different conditions with total 25k-45k cells expressing 16k-17k genes per set. Each condition has 3-11 samples.

I'd like to do a reactome GSA comparative analysis between the 2 conditions of these 4 sets. The ReactomeAnalysisRequest object of this largest combined data set is 4.5Gb.

Is this already too much for the server?  In the future, the data sets will be extended with more samples.
Quy

**Comment by jgriss** [comment]
Hi Quy,

This should work - and if it doesn't we'll give our best to make it work :-)

Do you use the `analyse_sc_clusters` function for your analysis?

Thanks,
Johannes
