### ISSUE TITLE
How can I save the heatmap from `plot_gsva_heatmap` with `ggplot2` ?

### ISSUE THREAD

**Issue by camilla0801** [reactome/ReactomeGSA#77]
Hi,

How can I save the heatmap from `plot_gsva_heatmap` with `ggplot2` ? when I try with ggsave as I'd usually do, it saves only the barplot from `plot_gsva_pathway` !

Thank you

**Comment by jgriss** [comment]
Hi,

Unfortunately, that's not possible. The `plot_gsva_heatmap` function does not use `ggplot2` but the `gplots::heatmap.2` function.

You can save the plot using the standard R approach, f.e.

```
png("my_image.png", width = 1000, height = 1000)
plot_gsva_heatmap(my_result)
dev.off()
```

**Comment by camilla0801** [comment]
thank you! I will the standard approach! :)
